jobs:
  5
cores: # is overruled by Snakemake config file
  20


use-conda:
  True
conda-frontend:
  mamba
conda-prefix: # avoid duplication of envs but it's impossible to simultaneously fetch 2 envs from 2 different snakemake projects
  "tools/conda" 


use-singularity:
  True
singularity-prefix:
  "tools/singularity"


printshellcmds: 
  True
keep-going: 
  True
rerun-incomplete: 
  True
# keep-incomplete: # good for debugging
#   True
