#! global params
nCORE:
  250 # cores used per single job


#! database:
GTDBTk_dir:
  "databases/GTDBTk"
GTDBTk_db:
  "databases/GTDBTk/GTDBTk_token"
TCDB_dir:
  "databases/tcdb"


#! modules to run:
ann_modules:
  - "prokka" #0
  - "KEGG_KO" #1
  - "KEGG_KM" #2
  - "KEGG_manual" #3
  - "antiSMASH" #4
  - "BioV_transp" #5
  - "blast_phytohormones" #6
  - "blast_vibrioferrin" #7
  - "blast_DMSP" #8
  - "dbCAN_CAZy" #9



#! module settings:

##! prokka
#!none

##! kofamscan
kegg_db:
  "databases/KEGG/kofamscan"
KM_str:
  "databases/KM_str.rds"

##! antismash
antim_db:
  "databases/antismash_token"

##! gblast (BioVx)
transp_set: # transporter set retained: all - B1_B12_B3_B7_SIDERO - WITH_SUBSTRATE - NO_GENERIC 
  "WITH_SUBSTRATE"

##! blast-phytohormones
phytohormones_db:
  "databases/custom_fasta/Protein_sequences_for_phytohormone_pathways_annotation.fasta"
phyhorm_suppl_tab: # table providing manually curated pathway structures 
  "databases/FunLuca_phytohormones.xlsx"

##! blast-vibrioferrin
vibrioferrin_db:
  "databases/custom_fasta/Protein_sequences_for_vibrioferrin_pathways_annotation_01mai20.fasta"

##! blast-DMSP
DMSP_db:
  "databases/custom_fasta/Protein_sequences_for_DMSP_pathways_annotation_21dec20.fasta"

##! dbCAN
dbCAN_db:
  "databases/CAZy"
CAZy_subs:
  "databases/selected_CAZy.tsv"

##! master table
KM_long_names:
  TRUE

##! Heat-maps
taxa_col:
  "databases/MY_taxa_cols.tsv"
min_trait_occur: # min number of genomes a trait should be bresent to be included in the heat-map
  3
min_tpm:
  5
dist_mt:
  "jaccard"
aggl_mt:
  "ward.D2"