cluster: 
  sbatch
    --nodes={resources.nodes}
    --time={resources.time}
    --partition={resources.partition}
    --qos={resources.qos}
    --job-name={rule}-{wildcards}
    --parsable # Required to pass job IDs to scancel


default-resources:
  - nodes=1
  - partition="zen3_0512" #! adjust to your cluster's environment
  - qos="p71863_0512" #! adjust to your cluster's environment
  - time="00:59:00"


jobs:
  100
cores: # is overruled by Snakemake config file
  88
cluster-cancel: # kill submitted jobs when killing a snakemake run
  scancel


use-conda:
  True
conda-frontend:
  mamba
conda-prefix: # avoid duplication of envs but it's impossible to simultaneously fetch 2 envs from 2 different snakemake projects
  "_tools/conda" 


use-singularity:
  True
singularity-prefix:
  "_tools/singularity"


printshellcmds: 
  True
keep-going: 
  True
rerun-incomplete: 
  True